localgov_base.settings:
  type: config_object
  label: 'LocalGov Base settings'
  mapping:
    localgov_base_remove_css:
      type: boolean
      label: 'Remove CSS libraries from base theme.'
    localgov_base_remove_js:
      type: boolean
      label: 'Remove JS libraries from base theme.'
    localgov_base_add_unpublished_background_colour:
      type: boolean
      label: 'Add background colour to unpublished content.'
    localgov_base_add_draft_note_to_unpublished_content:
      type: boolean
      label: 'Add "[Draft]" to title of unpublished content.'
    localgov_base_header_behaviour:
      type: enum
      label: 'Header behaviour'
      description: 'Choose whether the header should be sticky or not.'
      default: 'default'
      options:
        'default': 'Default - scrolls away with the page'
        'sticky': 'Sticky - remains at the top of the page'
        'appears_on_scroll': 'Scroll - appears when scrolling up'
