localgov_base.settings:
  type: config_object
  label: 'LocalGov Base settings'
  mapping:
    localgov_base_remove_css:
      type: boolean
      label: 'Remove CSS libraries from base theme.'
    localgov_base_remove_js:
      type: boolean
      label: 'Remove JS libraries from base theme.'
