name: Test localgovdrupal/localgov_base drupal-theme

on:
  push:
    branches:
      - '1.x'
  pull_request:
    branches:
      - '1.x'
  workflow_dispatch:

jobs:
  tests:
    uses: localgovdrupal/localgov_shared_workflows/.github/workflows/test-module.yml@feature/1.x/add-eslint-csslint-checks
    with:
      project: 'localgovdrupal/localgov_base'
      project_path: 'web/themes/contrib/localgov_base'
